#!/bin/bash

# start reading from text file given as an argument
while read -ra line; do
	a=${line[0]}
	b=${line[1]}
	c=${line[2]}
	for ((i=1; i<=c; i++)); do
		if (( i % a == 0 )) && (( i % b == 0 )); then
			printf "%s " FB
		elif (( i % a == 0 )); then
			printf "%s " F
		elif (( i % b == 0 )); then
			printf "%s " B
		else
			printf "%s " $i
		fi
	done
	printf "\n"
done < "$1"

